#!/bin/bash
set -e
cd /opt/TELEGRAM-BOT-AUTO-DM
git pull origin main
python3 -m venv .venv 2>/dev/null || true
. .venv/bin/activate
pip install -r requirements.txt
systemctl restart telegram-admin-bot
systemctl --no-pager --full status telegram-admin-bot
