from aiogram.types import InlineKeyboardButton,InlineKeyboardMarkup

def main_menu(owner=''):
 rows=[[InlineKeyboardButton(text='🆕 New Requests',callback_data='req:new'),InlineKeyboardButton(text='🕐 Pending',callback_data='req:old')],[InlineKeyboardButton(text='🤖 Auto-DM',callback_data='set:dm'),InlineKeyboardButton(text='⚡ Auto Accept',callback_data='set:accept')],[InlineKeyboardButton(text='📣 Post Sender',callback_data='post:start'),InlineKeyboardButton(text='⏰ Scheduled Posts',callback_data='post:schedules')],[InlineKeyboardButton(text='❤️ Auto Reaction',callback_data='reaction:page'),InlineKeyboardButton(text='📢 Broadcast',callback_data='broadcast:start')],[InlineKeyboardButton(text='👥 Users',callback_data='users:stats'),InlineKeyboardButton(text='📊 Statistics',callback_data='users:stats')],[InlineKeyboardButton(text='👨‍💼 Admins',callback_data='admins:help'),InlineKeyboardButton(text='📢 Channels',callback_data='channels:page')],[InlineKeyboardButton(text='⚙️ Settings',callback_data='settings'),InlineKeyboardButton(text='💎 Premium Emoji',callback_data='premium:page')],[InlineKeyboardButton(text='💾 Backup',callback_data='backup'),InlineKeyboardButton(text='❤️ Health',callback_data='health')],[InlineKeyboardButton(text='📞 CONTACT US FOR BOT',url=f'https://t.me/{owner.lstrip("@")}')]]
 return InlineKeyboardMarkup(inline_keyboard=rows)
def channel_list(rows,prefix='channel:select'):
 return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=f'{t[:32]}',callback_data=f'{prefix}:{c}') for c in [cid]] for cid,t,*_ in rows])
def post_targets(rows):
 return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=t[:38],callback_data=f'post:channel:{cid}')] for cid,t in rows]+[[InlineKeyboardButton(text='👥 All Users',callback_data='post:allusers')],[InlineKeyboardButton(text='❌ Cancel',callback_data='post:cancel')]])
def post_action(): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='🚀 Send Now',callback_data='post:sendnow'),InlineKeyboardButton(text='⏰ Schedule',callback_data='post:schedule')],[InlineKeyboardButton(text='❌ Cancel',callback_data='post:cancel')]])
def access(owner): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='📞 Contact Owner',url=f'https://t.me/{owner.lstrip("@")}')]])
